---
title: "4.3R"
output: html_document
date: "2023-11-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}
library(ordinal)
```

## Logit model.

```{r Call Data}
# Summon and relevel data.
supplies = read.csv(file = "../../data/Exercise4.3Data.csv",header=TRUE,sep=",")
  yrsbus.rel = relevel(factor(supplies$inbusiness), ref="< 1 year")
  first.rel = relevel(factor(supplies$firsttime), ref="yes")
  type.rel = relevel(factor(supplies$type), ref="furniture")
# Designate categories.
  amount.cat = factor(
    ifelse(supplies$amount < 10000, "1. <$10k",
           ifelse(supplies$amount > 30000, "3. >$30k", "2. $10k-$30k")))
```

```{r Develop Model}
summary(fitted.model<- clm(amount.cat ~ yrsbus.rel + first.rel + type.rel,
      data=supplies, link="logit"))

# Acquire degrees of freedom based on length of betas.
# Acquire p based on number of coefficients (threshold and predictors).
# Acquire n based on fitted.model nobs.
# Since the different models don't change these, this needs to only be done once.
deg_f = as.integer(length(fitted.model$beta)) 
p = as.integer(length(fitted.model$coefficients))
n = fitted.model$nobs
```

```{r Model Quality}
# Calculate AICC, BIC.
AICC = -2*logLik(fitted.model)+2*p*n/(n-p-1)

# Sprintf is used to create LaTex-ready table outputs.
cat(sprintf("\\begin{tabular}{ll}\\\\ \n"))
cat(sprintf("AIC & %s \\\\ \n", fitted.model$info$AIC))
cat(sprintf("AICC & %s \\\\ \n", AICC))
cat(sprintf("BIC & %s \n", BIC(fitted.model)))
cat(sprintf("\\end{tabular} \n"))

# Develop null model.
null.model = clm(amount.cat ~ 1, 
                 data=supplies, 
                 link="logit")

# Deviance test.
deviance = -2*(logLik(null.model)-logLik(fitted.model))
deviance_pval = pchisq(deviance,deg_f,lower.tail = FALSE)

cat(sprintf("\n"))
cat(sprintf("\\begin{tabular}{ll}
\\important{deviance} & \\important{pvalue}  \\\\ \n"))
cat(sprintf("%s & ", round(deviance,10)))
cat(sprintf("%s \n", round(deviance_pval,10)))
cat(sprintf("\\end{tabular}"))
```

```{r Logistic Prediction}
# Calculates a predicted value via the fitted model.
predicted = predict(fitted.model, data.frame(
  yrsbus.rel="1-5 years", first.rel= "no", type.rel= "electronics"), type="prob")

print(predicted)
```

## Probit model

```{r Call Data}
# Summon and relevel data.
supplies = read.csv(file = "../../data/Exercise4.3Data.csv",header=TRUE,sep=",")
  yrsbus.rel = relevel(factor(supplies$inbusiness), ref="< 1 year")
  first.rel = relevel(factor(supplies$firsttime), ref="no")
  type.rel = relevel(factor(supplies$type), ref="furniture")
# Designate categories.
  amount.cat = factor(
    ifelse(supplies$amount < 10000, "1. <$10k",
           ifelse(supplies$amount > 30000, "3. >$30k", "2. $10k-$30k")))
```

```{r Develop Model}
summary(fitted.model<- clm(amount.cat ~ yrsbus.rel + first.rel + type.rel,
      data=supplies, link="probit"))

# Acquire degrees of freedom based on length of betas.
# Acquire p based on number of coefficients (threshold and predictors).
# Acquire n based on fitted.model nobs.
# Since the different models don't change these, this needs to only be done once.
deg_f = as.integer(length(fitted.model$beta)) 
p = as.integer(length(fitted.model$coefficients))
n = fitted.model$nobs
```

```{r Model Quality}
# Calculate AICC, BIC.
AICC = -2*logLik(fitted.model)+2*p*n/(n-p-1)

# Sprintf is used to create LaTex-ready table outputs.
cat(sprintf("\\begin{tabular}{ll}\\\\ \n"))
cat(sprintf("AIC & %s \\\\ \n", fitted.model$info$AIC))
cat(sprintf("AICC & %s \\\\ \n", AICC))
cat(sprintf("BIC & %s \n", BIC(fitted.model)))
cat(sprintf("\\end{tabular} \n"))

# Develop null model.
null.model = clm(amount.cat ~ 1, 
                 data=supplies, 
                 link="probit")

# Deviance test.
deviance = -2*(logLik(null.model)-logLik(fitted.model))
deviance_pval = pchisq(deviance,deg_f,lower.tail = FALSE)

cat(sprintf("\n"))
cat(sprintf("\\begin{tabular}{ll}
\\important{deviance} & \\important{pvalue}  \\\\ \n"))
cat(sprintf("%s & ", round(deviance,10)))
cat(sprintf("%s \n", round(deviance_pval,10)))
cat(sprintf("\\end{tabular}"))
```

```{r Probit Prediction}
# Calculates a predicted value via the fitted model.
predicted = predict(fitted.model, data.frame(
  yrsbus.rel="1-5 years", first.rel= "no", type.rel= "electronics"), type="prob")

print(predicted)
```

## Cloglog model

```{r Call Data}
# Summon and relevel data.
supplies = read.csv(file = "../../data/Exercise4.3Data.csv",header=TRUE,sep=",")
  yrsbus.rel = relevel(factor(supplies$inbusiness), ref="< 1 year")
  first.rel = relevel(factor(supplies$firsttime), ref="no")
  type.rel = relevel(factor(supplies$type), ref="furniture")
# Designate categories.
  amount.cat = factor(
    ifelse(supplies$amount < 10000, "1. <$10k",
           ifelse(supplies$amount > 30000, "3. >$30k", "2. $10k-$30k")))
```

```{r Develop Model}
summary(fitted.model<- clm(amount.cat ~ yrsbus.rel + first.rel + type.rel,
      data=supplies, link="cloglog"))

# Acquire degrees of freedom based on length of betas.
# Acquire p based on number of coefficients (threshold and predictors).
# Acquire n based on fitted.model nobs.
# Since the different models don't change these, this needs to only be done once.
deg_f = as.integer(length(fitted.model$beta)) 
p = as.integer(length(fitted.model$coefficients))
n = fitted.model$nobs
```

```{r Model Quality}
# Calculate AICC, BIC.
AICC = -2*logLik(fitted.model)+2*p*n/(n-p-1)

# Sprintf is used to create LaTex-ready table outputs.
cat(sprintf("\\begin{tabular}{ll}\\\\ \n"))
cat(sprintf("AIC & %s \\\\ \n", fitted.model$info$AIC))
cat(sprintf("AICC & %s \\\\ \n", AICC))
cat(sprintf("BIC & %s \n", BIC(fitted.model)))
cat(sprintf("\\end{tabular} \n"))

# Develop null model.
null.model = clm(amount.cat ~ 1, 
                 data=supplies, 
                 link="logit")

# Deviance test.
deviance = -2*(logLik(null.model)-logLik(fitted.model))
deviance_pval = pchisq(deviance,deg_f,lower.tail = FALSE)

cat(sprintf("\n"))
cat(sprintf("\\begin{tabular}{ll}
\\important{deviance} & \\important{pvalue}  \\\\ \n"))
cat(sprintf("%s & ", round(deviance,10)))
cat(sprintf("%s \n", round(deviance_pval,10)))
cat(sprintf("\\end{tabular}"))
```

```{r Cloglog Prediction}
# Calculates a predicted value via the fitted model.
predicted = predict(fitted.model, data.frame(
  yrsbus.rel="1-5 years", first.rel= "no", type.rel= "electronics"), type="prob")

print(predicted)
```