---
title: "6.3R"
output: html_document
date: "2023-11-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Summon Libraries}
library(MASS)
```

```{r Call Data}
# Summon and relevel data.
allowance = read.csv(file = "../../data/Exercise6.3Data.csv",header=TRUE,sep=",")
  gender.rel = relevel(factor(allowance$gender), ref="M") 
  job.rel = relevel(factor(allowance$job), ref="yes") 
```

```{r Develop Model}
summary(fitted.model<- glm.nb(allowance ~ gender.rel + job.rel + age,
                           data=allowance))

# Acquires degrees of freedom based on coefficients minus 1.
# List format uses $.
deg_f = as.integer(length(fitted.model$coefficients)) - 1
```

```{r Model Quality}
# Develop null model.
null.model = glm.nb(allowance ~ 1,
                    data=allowance)

# Deviance test.
deviance = -2*(logLik(null.model)-logLik(fitted.model))
deviance_pval = pchisq(deviance,deg_f,lower.tail = FALSE)

cat(sprintf("\n"))
cat(sprintf("\\begin{tabular}{ll}
\\important{deviance} & \\important{pvalue}  \\\\ \n"))
cat(sprintf("%s & ", round(deviance,10)))
cat(sprintf("%s \n", round(deviance_pval,10)))
cat(sprintf("\\end{tabular}"))
```

```{r Prediction}
# Calculates a predicted value via the fitted model.
predict(fitted.model, data.frame
        (age=16, gender.rel ="M", job.rel ="no"),type="response")
```
