---
title: "6.9R"
output: html_document
date: "2023-11-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Summon Libraries}
library(pscl)
```

```{r Call Data}
# Summon and relevel data.
injuries = read.csv(file = "../../data/Exercise6.9Data.csv",header=TRUE,sep=",")
  gender.rel = relevel(factor(injuries$gender), ref="F") 
```

```{r Develop Model}
summary(fitted.model<- hurdle(ngameinjuries ~ gender.rel + nsports | npracticeinjuries,
                              data=injuries,
                              dist="negbin", zero.dist="binomial", link="logit"))

# Acquires degrees of freedom based on coefficients minus 2.
# List format uses $.
deg_f = as.integer(
  length(fitted.model$coefficients$count) +
  length(fitted.model$coefficients$zero)
  ) - 2
```

```{r Model Quality}
# Develop null model.
null.model = hurdle(ngameinjuries ~ 1,
                              data=injuries,
                              dist="negbin", zero.dist="binomial", link="logit")

# Deviance test.
deviance = -2*(logLik(null.model)-logLik(fitted.model))
deviance_pval = pchisq(deviance,deg_f,lower.tail = FALSE)

cat(sprintf("\n"))
cat(sprintf("\\begin{tabular}{ll}
\\important{deviance} & \\important{pvalue}  \\\\ \n"))
cat(sprintf("%s & ", round(deviance,10)))
cat(sprintf("%s \n", round(deviance_pval,10)))
cat(sprintf("\\end{tabular}"))
```

```{r Prediction}
# Calculates a predicted value via the fitted model.
predict(fitted.model, data.frame
        (gender.rel="M", nsports=2,npracticeinjuries=1),type="response")
```
